### ISSUE TITLE
Doesn't save account

### ISSUE THREAD

**Issue by ghost** [diamondburned/dissent#146]
Fedora 38. I downloaded it as a flatpack and after 2 launch of the program I need to re-enter the password. Does a beautiful picture require a new entry?

**Comment by diamondburned** [comment]
Did you tick the "Remember account" checkbox and any of the two checkboxes that it makes?

**Comment by largenton** [comment]
If the checkbox worked, then I would not write about the error

**Comment by pagenstedt** [comment]
Same here. 
btw beautiful app.

**Comment by tgm-git** [comment]
@Renceron it might be related to flatpak permissions. I needed to add org.freedesktop.secrets under Session Bus > Talks in order to be able to save/remember credentials.

I have detailed my debugging process in #141

**Comment by milkknife** [comment]
fixed with https://github.com/flathub/xyz.diamondb.gtkcord4/pull/9

**Comment by hybras** [comment]
Issue is resolved.
