### ISSUE TITLE
Rebrand to Dissent

### ISSUE THREAD

**Issue by bertob** [diamondburned/dissent#226]
It'd be great to fix the trademark issues and also bring it in line with the GNOME guidelines for [icons](https://developer.gnome.org/hig/guidelines/app-icons.html) and [app names](https://developer.gnome.org/hig/guidelines/app-naming.html). I just talked about this with Bart from Flathub at FOSDEM, would you be interested in help with branding?

**Comment by diamondburned** [comment]
I would be interested in seeing what we could come up with.

**Comment by cassidyjames** [comment]
Some ideas we chatted about with GNOME folks at FOSDEM playing off of "discord," but turning it positive:

- Codial
- Concord
- Concur
- Accord

Or if you wanted to keep the sort of negative of "discord":

- Dissent
- Quarrel
- Friction
- Chatter

**Comment by diamondburned** [comment]
I really like Cordial! It seems like it's used by an existing Discord bot for the name, but it should be fine.

Quarrel is also really good, but it is currently used by [WinAppCommunity/Quarrel](https://github.com/WinAppCommunity/Quarrel) which is some abandoned Discord client for the Xbox?

**Comment by diamondburned** [comment]
Thank you!

**Comment by bertob** [comment]
> I really like Cordial! It seems like it's used by an existing Discord bot for the name, but it should be fine.

Yeah, probably fine since it's unlikely to be confused with the bot.

Alternatively I also like Dissent, it has the same initial as Discord and is similar in length and meaning.

**Comment by diamondburned** [comment]
Dissent also seems nice. There's no bot or client named that yet.

**Comment by bertob** [comment]
Cool, should we start looking into an icon for "Dissent"?

**Comment by diamondburned** [comment]
> Cool, should we start looking into an icon for "Dissent"?

Yes!

**Comment by bertob** [comment]
Here's a first attempt:

![image](https://github.com/diamondburned/gtkcord4/assets/1908896/e017d4aa-2a5c-4adb-8e71-e5f9a6211fb7)

**Comment by diamondburned** [comment]
How would the icon look like without the tiny buttons on top?

**Comment by bertob** [comment]
Not sure that works, ends up looking a bit empty at the top and bottom:

![image](https://github.com/diamondburned/gtkcord4/assets/1908896/5f1995f3-780d-4414-9fda-b925a15e2fa2)

What are your specific concerns with the buttons? If it's just too many colors, we could also do something like this:

![image](https://github.com/diamondburned/gtkcord4/assets/1908896/4ed40f3c-afc9-4882-9807-b3cf5c7f8682)

**Comment by diamondburned** [comment]
I do think the grey buttons look nicer for larger sizes, but the one without the buttons look a bit nicer for smaller sizes.

Would it be possible to also try the icon out with the purple of the current logo? Also, could you check the vertical alignment of the icon? I think it's a bit too low:

![b](https://github.com/diamondburned/gtkcord4/assets/8463786/87768282-093b-469b-b9f5-d8f48ebcd1a8)

**Comment by bertob** [comment]
> I do think the grey buttons look nicer for larger sizes, but the one without the buttons look a bit nicer for smaller sizes.

Icons should be optimized to look good at 64px first and foremost, 32px support is best-effort. That said, looking at this again I don't have a super strong opinion, the version with top buttons might be fine too.

Quickly tried the standard GNOME purple, but I think for a third party app like this a more custom color like the one from the original concepts would be nicer.

![image](https://github.com/diamondburned/gtkcord4/assets/1908896/5de99a5e-3dd0-4486-ac98-75273e752a8a)

As for the vertical alignment, apps are not supposed to all be vertically centered, but rather be oriented on the baseline. For chat apps that's extra tricky since you have the point at the bottom. The current shape is what we ended up with as a compromise when doing the Fractal icon, and I reused that shape here.

**Comment by diamondburned** [comment]
Ah, that makes sense! The [blue-with-grey-buttons icon](https://private-user-images.githubusercontent.com/1908896/307191317-4ed40f3c-afc9-4882-9807-b3cf5c7f8682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjExNjMsIm5iZiI6MTcwODgyMDg2MywicGF0aCI6Ii8xOTA4ODk2LzMwNzE5MTMxNy00ZWQ0MGYzYy1hZmM5LTQ4ODItOTgwNy1iM2NmNWM3Zjg2ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMDAyNzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRiZTZjZWEyMzhhN2RlODM1YTVjNmQxOTg4Y2QzMjFiODZjMzlhNWQ0YWFlNTM1Y2Y1MDFiN2QyNjQxMmMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aqy6MthIJ-7n3cYDkK8F5z-7JlHBKccYkTeMLaJpQNY) looks nicest, then!

Would you want to create a PR with the new SVGs and PNGs? I can handle the rebranding of the name itself soon.

**Comment by bertob** [comment]
> Ah, that makes sense! The [blue-with-grey-buttons icon](https://private-user-images.githubusercontent.com/1908896/307191317-4ed40f3c-afc9-4882-9807-b3cf5c7f8682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjExNjMsIm5iZiI6MTcwODgyMDg2MywicGF0aCI6Ii8xOTA4ODk2LzMwNzE5MTMxNy00ZWQ0MGYzYy1hZmM5LTQ4ODItOTgwNy1iM2NmNWM3Zjg2ODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMDAyNzQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRiZTZjZWEyMzhhN2RlODM1YTVjNmQxOTg4Y2QzMjFiODZjMzlhNWQ0YWFlNTM1Y2Y1MDFiN2QyNjQxMmMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aqy6MthIJ-7n3cYDkK8F5z-7JlHBKccYkTeMLaJpQNY) looks nicest, then!

That link doesn't seem to work here, but yeah I'd be happy to make a PR :)

**Comment by diamondburned** [comment]
Could we have a monochrome symbolic version of the icon? I want to try and make a loading screen similar to Tuba's:

![image](https://github.com/diamondburned/dissent/assets/8463786/9c2fff6f-b8fc-4b86-a74f-a28826440fa5)

**Comment by diamondburned** [comment]
Whoops, turns out we already have a symbolic icon o.o

**Comment by bertob** [comment]
Ah sorry, forgot to reply. Yeah, there's already a symbolic, but it's not recommended to use it on loading screens like Tuba did (I think it was already changed to just be a centered spinner without a symbolic).
