### ISSUE TITLE
DM list immediately fades away after open

### ISSUE THREAD

**Issue by amyipdev** [diamondburned/dissent#241]
I can load the client fine, and most functionality works, but my DM drawer is very broken.

After clicking on the drawer, I can see the list for about 0.25s:
![image](https://github.com/diamondburned/dissent/assets/46307646/69092793-5bcc-4f34-923f-811b8035dde9)

It then immediately disappears:
![image](https://github.com/diamondburned/dissent/assets/46307646/493939ce-1a89-4d49-baa0-5aae30a30adc)

**Comment by amyipdev** [comment]
If I Ctrl-K into a DM then this bug does not occur.

**Comment by diamondburned** [comment]
Is there anything about this in Logs?

**Comment by tfuxu** [comment]
I've had the same issue on the latest commit. To fix that, you need to click the first DM before the fade-out animation kicks in.
I think this might be an just an unimplemented behavior that happens only if you login to Dissent for the first time. To fix that in code, you probably just need to fetch the first DM from the vector and select it in the ListBox.

**Comment by diamondburned** [comment]
Interesting, that's really helpful.

**Comment by maxrdz** [comment]
The fix mentioned above is also what I found out you could do to work around the bug. But yeah, also happened to me once, although it doesn't happen anymore.

**Comment by diamondburned** [comment]
https://github.com/diamondburned/dissent/commit/0e869e255e28213510e7fb346044da8cebb8ea15 should fix this issue.
