### ISSUE TITLE
Update Flatpack info

### ISSUE THREAD

**Issue by TipsyTheCat** [diamondburned/dissent#248]
The [Flathub page](https://flathub.org/apps/so.libdb.gtkcord4) is out of date (v0.0.19) with the old name and the [Flathub link](https://flathub.org/apps/so.libdb.dissent) in the readme with the new name leads to a 404.

**Comment by diamondburned** [comment]
This is blocking on https://github.com/flathub/so.libdb.gtkcord4/issues/9.

**Comment by diamondburned** [comment]
https://github.com/flathub/so.libdb.gtkcord4/issues/9 is closed, so closing this issue as well.
