### ISSUE TITLE
Scrolling is laggy when mouse is hovering over messages, smooth when hovering over blank area

### ISSUE THREAD

**Issue by carterprince** [diamondburned/dissent#254]
Title -- this also happens for the channel list. Is there an easy fix for this?

**Comment by diamondburned** [comment]
Interesting. Are you scrolling using a touchpad? Do you know if your application is rendering via Cairo (software) or OpenGL (hardware)? You should be able to check that via <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>, in the Global menu.

**Comment by carterprince** [comment]
Yes, I am scrolling with a touchpad. It mainly happens in fullscreen when in a channel with a lot of embeds/images.
![image](https://github.com/diamondburned/dissent/assets/11081492/883c4806-b8c6-4668-8777-d4f158cc9832)

**Comment by carterprince** [comment]
Here's a video of this effect:

https://github.com/diamondburned/dissent/assets/11081492/04e79059-012d-42d8-9c61-8de5e0603496

**Comment by diamondburned** [comment]
If I have to guess, it's the hover background transition. I'll see if I can experiment with it.

**Comment by algj** [comment]
Yeah, the lag was unbearable for me on a low end system...

**Comment by diamondburned** [comment]
> Yeah, the lag was unbearable for me on a low end system...

Does turning on the `Reduce Animation` accessibility option help with this?
![image](https://github.com/user-attachments/assets/a7d82f4e-4a85-4cb5-9542-46ef1790e8be)

**Comment by algj** [comment]
I updated my Arch system and the performance problems went away! That's weird.

**Comment by LordRusk** [comment]
> > Yeah, the lag was unbearable for me on a low end system...
> 
> Does turning on the `Reduce Animation` accessibility option help with this? ![image](https://private-user-images.githubusercontent.com/8463786/365937200-a7d82f4e-4a85-4cb5-9542-46ef1790e8be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTUxMDIsIm5iZiI6MTcyNjUxNDgwMiwicGF0aCI6Ii84NDYzNzg2LzM2NTkzNzIwMC1hN2Q4MmY0ZS00YTg1LTRjYjUtOTU0Mi00NmVmMTc5MGU4YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTkyNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjczN2VhNzFlMjE5OGVhODRhNTg4YWUyNjVkOTcyMzY0NTk3NTIwOGU0YWZiZTA3MWIxMWJmMmE2MGM4ZGE0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mUzcvFx7BSBe90RteD2ZyFKw6D7J1Qqb-9vJeMFROAk)

excuse the dumb question...what program is that? i cannot find those settings in dissent...

**Comment by algj** [comment]
I consider this a solved issue, might've been a bug with the renderer. I think we can close this issue.
