### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [diamondburned/dissent#261]
Since Dissent is officially available on Flathub, would you consider verifying it to show people who discover it through Flathub that it is an official package? Here is the documentation for getting verified: https://docs.flathub.org/docs/for-app-authors/verification

**Comment by diamondburned** [comment]
@tfuxu, if you have the app UUID, I can put it onto my webserver (libdb.so) for this.

**Comment by tfuxu** [comment]
Sure, here's UUID:
`6c6b3f85-6d8d-4637-9717-07bab96d5139`
You need to put in inside a file in https://libdb.so/.well-known/org.flathub.VerifiedApps.txt

**Comment by diamondburned** [comment]
> https://libdb.so/.well-known/org.flathub.VerifiedApps.txt

This is now live:

```
―❤―▶ curl -L https://libdb.so/.well-known/org.flathub.VerifiedApps.txt
# so.libdb.dissent
6c6b3f85-6d8d-4637-9717-07bab96d5139
```

**Comment by tfuxu** [comment]
Done.
![Screenshot 2024-03-31 at 00-35-31 Dissent Flathub](https://github.com/diamondburned/dissent/assets/73042332/42629346-ad8d-4d59-818c-3b0862912498)

**Comment by Roman19S** [comment]
It looks like the verification went through. Thank you all for acting so quickly!
![image](https://github.com/diamondburned/dissent/assets/30319719/ab28fb2f-a5ed-40d7-819d-d5affc8f2864)
