### ISSUE TITLE
failed to apply http request options - context canceled

### ISSUE THREAD

**Issue by Nydragon** [diamondburned/dissent#269]
Source: Flatpak
Version: v0.0.22

I get the following error on application start `failed to apply http request options - context canceled`.

The chatrooms only appear for a brief moment when clicking on the text message icon at the top left of the window.

**Comment by Nydragon** [comment]
Update: This only was an error up until i exchange a message with somebody in private message.

Guilds had no problem loading, so it is only related to private messages.

**Comment by diamondburned** [comment]
It seems this might have to do with #241. I'll try to look into #241 first.

**Comment by diamondburned** [comment]
#241 is fixed. Could you try the latest pre-release and see if you can replicate that bug? You can try and delete `~/.config/gtkcord4` if you cannot replicate it the first time.

**Comment by diamondburned** [comment]
Closing since it's highly likely that this is just #241.
