### ISSUE TITLE
0.0.23 release assets are missing files

### ISSUE THREAD

**Issue by txtsd** [diamondburned/dissent#271]
```
λ tree src
src
├── bin
│   └── dissent
└── share
    ├── applications
    │   └── so.libdb.dissent.desktop
    ├── dbus-1
    │   └── services
    │       └── so.libdb.dissent.service
    └── icons
        └── hicolor
            └── 256x256
                └── apps
                    └── so.libdb.dissent.svg

10 directories, 4 files
```

Ideally it would have the metainfo file, the symbolic SVG, as well as the symbolic action SVGs.

**Comment by diamondburned** [comment]
> the symbolic SVG, as well as the symbolic action SVGs

Aren't these already embedded in the Dissent binary? Do we need them here?

**Comment by txtsd** [comment]
Is that how it works?

I copy them to the right directories in the non-binary (pun not intended) AUR packages.
See: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dissent#n44
See: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dissent-git#n50

**Comment by diamondburned** [comment]
> Is that how it works?

Yeah, they shouldn't be needed.

**Comment by diamondburned** [comment]
A minor thing that's wrong is that the .svg should be in `scalable`, not `256x256`.

**Comment by diamondburned** [comment]
This should be fixed in the pre-release. I don't expect these icon files to actually be used since they may override system icons and the binary already has them embedded, but please make an issue if that causes issues.

**Comment by txtsd** [comment]
Alright, thank you!
