### ISSUE TITLE
can't login (No such host : discord.com)

### ISSUE THREAD

**Issue by LukIsHere** [diamondburned/dissent#274]
because of error 
 Failed to login:
L Request failed:
L Post "https://discord.com/api/v9/auth/ login":
L Dial tep:
L Lookup discord.com:
L No such host.

i can't login on latest flathub version (v0.0.23)
I am using droidian testing arm64
and i am sure i have internet connection
![image](https://github.com/diamondburned/dissent/assets/92756992/78bf1af0-0d18-4b78-8f68-d102a0b2c3b6)
i doubt trying token login would fix anything since it seams like it can't make a request to discord

**Comment by m-attz** [comment]
It seems that the specific endpoint it is trying to send a request to doesn't exist. 

Try a token login for now (if you have not already) because it should send a request to a different endpoint that deals with tokens.

**Comment by diamondburned** [comment]
It looks like a DNS issue, but definitely try to do the token login!

**Comment by LukIsHere** [comment]
i don't know why but now it just works
