### ISSUE TITLE
Bug, cannot build on powerpc 32 bit

### ISSUE THREAD

**Issue by yumikonoua** [diamondburned/dissent#291]
im trying to build dissent on a powerpc 32 bit mac with linux(debian sid) and when I try to compile from source it says:
"fienix@fienix:~$ go install -v libdb.so/dissent@latest
go: libdb.so/dissent@latest (in libdb.so/dissent@v0.0.25): go.mod:3: invalid go version '1.21.0': must match format 1.23"

how i can fix?

**Comment by diamondburned** [comment]
Your Go version is too old, I think. You need Go 1.21 or later.

**Comment by yumikonoua** [comment]
I will upgrade, thanks

**Comment by diamondburned** [comment]
Closing since stale. Feel free to reopen.
