### ISSUE TITLE
Enhancement: Disable Conversation Summaries

### ISSUE THREAD

**Issue by Iguessthiswasinevitable** [diamondburned/dissent#293]
There's no way I can find to disable the AI-generated conversation summaries in Dissent. Because they're dropped directly into the chat, they're incredibly irritating when you're just trying to talk to people, and like most LLM-based tools they're also hilariously inaccurate most of the time. The full feature client allows you to easily disable the summaries. I'd just like a toggle I can hit to turn them off, or at least to stop them showing up in the chat itself (since there's already a highlights button you can hit to see them all listed if you really want to).

Thanks for all your hard work.

**Comment by diamondburned** [comment]
There actually is! It's under <kbd>Preferences</kbd> then <kbd>Messages</kbd>.

![image](https://github.com/user-attachments/assets/7b493988-0ae7-4b76-9f73-203d910eaf3f)

**Comment by Iguessthiswasinevitable** [comment]
Hi. I was too embarrassed to respond at the time, but I wanted to thank you for pointing this out without being condescending about it.
