### ISSUE TITLE
[Bug] Mouse becoming larger when entering Dissent window

### ISSUE THREAD

**Issue by samolego** [diamondburned/dissent#295]
ik, it's a strange bug, but mouse cursor grows quite a bit when entering the Dissent window.
I'm using Ultramarine Linux 40, KDE Plasma (6) edition.
[Screencast_20240802_213442.webm](https://github.com/user-attachments/assets/a8663c36-6b85-4f40-8b52-46f1cc8af33d)
![Screenshot_20240802_214139](https://github.com/user-attachments/assets/98dc40a3-412d-427d-86b4-d5e2b4553db1)
![Screenshot_20240802_214144](https://github.com/user-attachments/assets/d1a74675-ffa6-4906-9089-c368acbd72c2)

**Comment by diamondburned** [comment]
This is more of a GTK misconfiguration bug than a Dissent bug. You can confirm this with any GTK4 application. If that's not the case, feel free to reopen this issue, although I won't really know what to do about it.
