### ISSUE TITLE
Messages column is centered

### ISSUE THREAD

**Issue by caiigee** [diamondburned/dissent#301]
![2024-08-21T15:49:31,541294837+02:00](https://github.com/user-attachments/assets/2ce843ea-4390-45a5-a2d5-7fd45dbabb7b)

As the title and the image suggest, my messages column is centered instead of aligned to the left.

I am running Arch Linux (6.10.5-arch1-1) and Hyprland.
I have installed Dissent through Flathub.
I have tried changing the messages column width, but nothing seems to be happening.
No error is shown in the logs.

**Comment by diamondburned** [comment]
> I have tried changing the messages column width, but nothing seems to be happening.

You need to switch to a different channel for this to take effect.

> my messages column is centered instead of aligned to the left

This is intentional. Set to a really large width to work around this.
