### ISSUE TITLE
Enhancement: Show messages in rich-text preview instead of Markdown

### ISSUE THREAD

**Issue by amethystgosling163** [diamondburned/dissent#321]
I saw that this message I posted from Discord in the browser that isn't showing up in a rich-text Markdown preview but instead as Markdown text.
![Screenshot from 2024-10-12 17-54-34](https://github.com/user-attachments/assets/1c8c3b3d-7588-458f-9191-996e9aab42eb)

This is a young project, and so I thought that it might not even have this feature and made this FR.

**Comment by diamondburned** [comment]
It does. It just doesn't have Markdown links. You're free to open a separate issue for that, though.
