### ISSUE TITLE
Can't Change Theme

### ISSUE THREAD

**Issue by eeriemyxi** [diamondburned/dissent#327]
I looked around for a support forum or something like that but I couldn't find anything. So I thought I would make a new issue.

I installed the Flatpak version and immediately got flashed by the light theme; then I went to settings and the only relevant setting I could find there was "Use Discord's color preference." I tried toggling it on and off but it doesn't do anything. And yes my Discord account's theme is indeed set to dark mode.

Is there a solution to this? I can't bear this light theme at all.

I tried installing Flatseal then allowing access to `/home/myxi/.themes` and `/home/myxi/.icons` but it didn't do anything. I also sensibly copy-pasted some commands from [here](https://askubuntu.com/questions/1403931/how-to-apply-system-theme-to-flatpak-apps-that-use-gtk4) but that didn't do anything too.

Then I tried running the native build for amd64, but when I run `./bin/dissent`, I get this:
`./bin/dissent: error while loading shared libraries: libspelling-1.so.1: cannot open shared object file: No such file or directory`. My distribution is Ubuntu 22.04. I went as far as downloading the `.deb` file for that library from Debian repositories but I couldn't install it because it would break other packages. What do I do? TBH I couldn't care less about spell-checking; if there is a way to just straight up ignore this thing, I am more than willing to do so.

```
myxi :: ~/Documents/trash » apt search ^libgspell                           127 ↵
Sorting... Done
Full Text Search... Done
libgspell-1-2/jammy,now 1.9.1-4 amd64 [installed,automatic]
  spell-checking library for GTK+ applications

libgspell-1-common/jammy,jammy,now 1.9.1-4 all [installed,automatic]
  libgspell architecture-independent files

libgspell-1-dev/jammy,now 1.9.1-4 amd64 [installed]
  spell-checking library for GTK+ applications - development files

libgspell-1-doc/jammy,jammy 1.9.1-4 all
  spell-checking library for GTK+ applications - documentation

myxi :: ~/Documents/trash » apt search ^libspell
Sorting... Done
Full Text Search... Done
myxi :: ~/Documents/trash » apt search ^libspelling
Sorting... Done
Full Text Search... Done
myxi :: ~/Documents/trash » apt search ^libgspelling
Sorting... Done
Full Text Search... Done
```

**Comment by eeriemyxi** [comment]
I managed to get it to work. The "fix" is to install Distrobox and set up an Arch Linux container. You install the `dissent-bin` AUR, install everything it errors at, then eventually follow [this](https://github.com/diamondburned/dissent/issues/313#issuecomment-2365297532). This is better than the Flatpak but it's cumbersome at best even so.
![image](https://github.com/user-attachments/assets/df40d56a-9de0-466a-a366-09abf0710710)

**Comment by diamondburned** [comment]
> I installed the Flatpak version

It's hard to get Flatpak to see your native theme. I think you'll have to poke around with this more. Dissent, with the "Use Discord's color preference" option disabled, should adhere to your system's dark theme preference.
