### ISSUE TITLE
Enhancement: make a copr release

### ISSUE THREAD

**Issue by CodedIsTaken** [diamondburned/dissent#329]
Considering you have nix and AUR versions, it is only logically fair to open a copr version, I can also maintain one myself but it puts more work onto me since i maintain multiple copr repos.

**Comment by diamondburned** [comment]
Sorry, I don't actually have Nix and AUR versions. They're all maintained by someone else. I currently don't maintain packages for any distro myself.

**Comment by CodedIsTaken** [comment]
Then send this notification to the maintainer.

**Comment by CodedIsTaken** [comment]
> Sorry, I don't actually have Nix and AUR versions. They're all maintained by someone else. I currently don't maintain packages for any distro myself.

Then just send the request for the copr repo to the maintainer of the repos then.

**Comment by diamondburned** [comment]
The maintainers of those packages made the packages because it's for the distros that they use. I don't have control over what they do. If you really want to use Dissent on Fedora, you can get the Flatpak version like I did.

**Comment by CodedIsTaken** [comment]
> The maintainers of those packages made the packages because it's for the distros that they use. I don't have control over what they do. If you really want to use Dissent on Fedora, you can get the Flatpak version like I did.

No thanks, I'll maintain my own version.

**Comment by CodedIsTaken** [comment]
Update: here's a better more easier method.

ask the guys of this repo to maintain a package for dissent https://terra.fyralabs.com/
