### ISSUE TITLE
Bug: Log in using email with TOTP 2FA code fails

### ISSUE THREAD

**Issue by devurandom** [diamondburned/dissent#333]
When I try to log in using my email and password and a 2FA code, I get (always; I tried many times):
```
Error: cannot login
└ Failed to login with 2FA:
    └ Discord 400 error:
        └ Invalid two-factor code.
```

I can log in with the same email and password and TOTP generator using Vesktop.

Sidenote: It appears that I get logged out of Vesktop, when I try to log into Dissent.

**Comment by diamondburned** [comment]
You should definitely log in with token instead. You being logged out of Discord when logging in on Dissent is a *very* bad sign.

**Comment by diamondburned** [comment]
Closing this issue for now as I'm not willing to look into this. It's better to consider removing email login support entirely.
