### ISSUE TITLE
About dialog

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/dissent#74]
The application currently has an About button, but it does nothing. The About dialog should pop up.

The About dialog should try and facilitate Go 1.18's [BuildSetting](https://pkg.go.dev/runtime/debug@go1.19.1#BuildSetting) to get the VCS information and determine whether the stable or nightly logo should be used.

**Comment by diamondburned** [comment]
It would also be nice if the Nix build files are smart enough to use the actual logo for CI release builds.

**Comment by DodoLeDev** [comment]
You should create the About window by following the new [AdwAboutDialog design](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.AboutWindow.html)! :smiley:

**Comment by diamondburned** [comment]
I'll just use what's already there, which is [GtkAboutDialog](https://docs.gtk.org/gtk4/class.AboutDialog.html). It works perfectly fine.

**Comment by diamondburned** [comment]
After some consideration, I'm going with AdwAboutDialog anyway. There's a huge downside of the minimum version required being Adwaita v1.2.x, but whatever.

**Comment by diamondburned** [comment]
Actually? Nevermind.

![image](https://user-images.githubusercontent.com/8463786/223328782-35243aef-d87f-4cb0-ad17-588fc7e4bd0e.png)

There's no way for me to use a Paintable for the application icon, and I really don't want to deal with GTK's weird icon API that's made for languages like C.

I'll probably settle with a GtkAboutDialog.

**Comment by diamondburned** [comment]
There we go.

![image](https://user-images.githubusercontent.com/8463786/223330184-0159659b-4172-4973-b433-fde8b0209472.png)

**Comment by hybras** [comment]
This is done per #177 ?
