### ISSUE TITLE
Feature request: load older messages

### ISSUE THREAD

**Issue by TriVoxel** [diamondburned/dissent#86]
It seems as though GTKcord4 only loads the most recent messages. It appears to be hard-coded. It would be nice if the user could either increase this manually in settings, or if the app could detect the user scrolling to the very top and then load more messages.

**Comment by asdfghjkl403622** [comment]
Realizing that this has been bumped by the project creator, what's stopping this from being implemented? something with the discord api?

**Comment by diamondburned** [comment]
Nothing, really. I just haven't been paying much attention to this project as often as I should. Every time I need to see the backlog, I just use my phone.

Having backlog support would be very nice, although it won't be very trivial to implement it nicely. There are some edge cases that needed to be taken into consideration, e.g. whether new messages should pause being loaded while the user is scrolled all the way up.

**Comment by asdfghjkl403622** [comment]
that's alright! but if you have the time, pretty please implement it as this is the best linux mobile discord client afaik!

**Comment by hybras** [comment]
This is done? I see a "Show more" button
